// ===================================
// 💪 Workout Summary Component
// ===================================
// Step 4 (Optional) - Final workout summary

import React from 'react';
import { Download, RotateCcw, ChevronLeft } from 'lucide-react';

const WorkoutSummary = ({
  equipment,
  muscles,
  exercises,
  onBack,
  onReset
}) => {
  // ============================================
  // Download workout as PDF/Text
  // ============================================

  const downloadWorkout = () => {
    let workoutText = `MUSCLE DYNAMICS - PERSONALIZED WORKOUT PLAN\n`;
    workoutText += `Generated: ${new Date().toLocaleString()}\n`;
    workoutText += `${'='.repeat(50)}\n\n`;

    workoutText += `WORKOUT CONFIGURATION\n`;
    workoutText += `${'─'.repeat(50)}\n`;
    workoutText += `Equipment: ${equipment.join(', ')}\n`;
    workoutText += `Target Muscles: ${muscles.join(', ')}\n`;
    workoutText += `Total Exercises: ${exercises.length}\n\n`;

    workoutText += `EXERCISE ROUTINE\n`;
    workoutText += `${'─'.repeat(50)}\n`;

    exercises.forEach((exercise, index) => {
      workoutText += `\n${index + 1}. ${exercise.name.toUpperCase()}\n`;
      workoutText += `Equipment: ${exercise.equipment}\n`;
      workoutText += `Primary Muscles: ${exercise.primaryMuscles.join(', ')}\n`;
      if (exercise.secondaryMuscles && exercise.secondaryMuscles.length > 0) {
        workoutText += `Secondary Muscles: ${exercise.secondaryMuscles.join(', ')}\n`;
      }
      workoutText += `Reps: ${exercise.reps || 'N/A'}\n`;
      workoutText += `Sets: ${exercise.sets || 'N/A'}\n`;
      workoutText += `Rest: ${exercise.restSeconds ? exercise.restSeconds + 's' : 'N/A'}\n`;

      if (exercise.instructions && exercise.instructions.length > 0) {
        workoutText += `\nInstructions:\n`;
        exercise.instructions.forEach((instruction, i) => {
          workoutText += `  ${i + 1}. ${instruction}\n`;
        });
      }
      workoutText += '\n';
    });

    workoutText += `${'='.repeat(50)}\n`;
    workoutText += `💪 Generated by Muscle Dynamics\n`;

    // Create blob and download
    const blob = new Blob([workoutText], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `muscle-dynamics-workout-${new Date().getTime()}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    window.URL.revokeObjectURL(url);
  };

  // Calculate workout stats
  const totalMuscles = new Set(
    exercises.flatMap(e => [...(e.primaryMuscles || []), ...(e.secondaryMuscles || [])])
  ).size;

  // ============================================
  // Render
  // ============================================

  return (
    <div className="space-y-8">
      {/* Success banner */}
      <div className="bg-gradient-to-r from-red-600 to-red-700 rounded-2xl p-8 text-white text-center space-y-3 shadow-lg">
        <div className="text-5xl">🎉</div>
        <h2 className="text-3xl md:text-4xl font-bold">Workout Plan Ready!</h2>
        <p className="text-red-100 text-lg">
          Your personalized fitness routine has been created
        </p>
      </div>

      {/* Stats grid */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <div className="bg-gray-800 border border-gray-700 rounded-lg p-6 text-center">
          <p className="text-gray-400 text-sm mb-2">Total Exercises</p>
          <p className="text-3xl font-bold text-red-600">{exercises.length}</p>
        </div>

        <div className="bg-gray-800 border border-gray-700 rounded-lg p-6 text-center">
          <p className="text-gray-400 text-sm mb-2">Muscle Groups</p>
          <p className="text-3xl font-bold text-blue-600">{totalMuscles}</p>
        </div>

        <div className="bg-gray-800 border border-gray-700 rounded-lg p-6 text-center">
          <p className="text-gray-400 text-sm mb-2">Equipment Types</p>
          <p className="text-3xl font-bold text-amber-600">{equipment.length}</p>
        </div>

        <div className="bg-gray-800 border border-gray-700 rounded-lg p-6 text-center">
          <p className="text-gray-400 text-sm mb-2">Est. Duration</p>
          <p className="text-3xl font-bold text-emerald-600">45-60m</p>
        </div>
      </div>

      {/* Configuration summary */}
      <div className="bg-gray-800 border border-gray-700 rounded-lg p-6 space-y-4">
        <h3 className="text-xl font-bold text-white">Your Configuration</h3>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {/* Equipment */}
          <div>
            <p className="text-gray-400 font-medium mb-3">Equipment Used:</p>
            <div className="flex flex-wrap gap-2">
              {equipment.map((eq) => (
                <span key={eq} className="badge bg-red-600 text-white">
                  {eq}
                </span>
              ))}
            </div>
          </div>

          {/* Muscles */}
          <div>
            <p className="text-gray-400 font-medium mb-3">Target Muscles:</p>
            <div className="flex flex-wrap gap-2">
              {muscles.map((muscle) => (
                <span key={muscle} className="badge bg-blue-600 text-white">
                  {muscle}
                </span>
              ))}
            </div>
          </div>
        </div>
      </div>

      {/* Exercise summary list */}
      <div className="space-y-3">
        <h3 className="text-xl font-bold text-white">Exercise Breakdown</h3>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {exercises.map((exercise, index) => (
            <div
              key={exercise._id}
              className="bg-gray-800 border border-gray-700 rounded-lg p-4 hover:border-red-600 transition-colors"
            >
              <div className="flex items-start gap-3">
                <div className="flex-shrink-0 w-8 h-8 rounded-full bg-red-600 text-white flex items-center justify-center font-bold text-sm">
                  {index + 1}
                </div>
                <div className="flex-1">
                  <h4 className="font-semibold text-white text-sm">{exercise.name}</h4>
                  <p className="text-gray-400 text-xs mt-1">
                    {exercise.reps || '8-12'} reps × {exercise.sets || '3'} sets
                  </p>
                  <p className="text-gray-500 text-xs mt-1">
                    {exercise.primaryMuscles.join(', ')}
                  </p>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Tips section */}
      <div className="bg-blue-600/20 border border-blue-600 rounded-lg p-6 space-y-3">
        <h3 className="text-lg font-bold text-blue-300">💡 Workout Tips</h3>
        <ul className="space-y-2 text-blue-200 text-sm">
          <li>• Warm up for 5-10 minutes before starting the workout</li>
          <li>• Follow the prescribed reps and sets for optimal results</li>
          <li>• Rest between sets as recommended</li>
          <li>• Maintain proper form - quality over quantity</li>
          <li>• Stay hydrated throughout your workout</li>
          <li>• Cool down and stretch for 5-10 minutes after</li>
          <li>• Complete this routine 3-4 times per week</li>
        </ul>
      </div>

      {/* Action buttons */}
      <div className="flex gap-4 flex-wrap justify-center pt-4">
        <button
          onClick={downloadWorkout}
          className="btn btn-primary px-8 py-3 rounded-lg flex items-center gap-2 font-semibold hover:shadow-lg hover:shadow-red-600/50"
        >
          <Download size={20} />
          <span>Download Plan</span>
        </button>

        <button
          onClick={onBack}
          className="btn btn-secondary px-8 py-3 rounded-lg flex items-center gap-2 font-semibold"
        >
          <ChevronLeft size={20} />
          <span>Back to Exercises</span>
        </button>

        <button
          onClick={onReset}
          className="btn btn-outline px-8 py-3 rounded-lg flex items-center gap-2 font-semibold"
        >
          <RotateCcw size={20} />
          <span>New Workout</span>
        </button>
      </div>

      {/* Disclaimer */}
      <div className="bg-gray-800 border border-gray-700 rounded-lg p-4 text-center text-gray-400 text-sm">
        <p>
          💪 Consult a fitness professional before starting a new exercise program.
          Results depend on consistent training and proper nutrition.
        </p>
      </div>
    </div>
  );
};

export default WorkoutSummary;